"""feat: bloque F

Revision ID: 47ad3b294cbb
Revises: 51f33345d418
Create Date: 2026-04-26 19:18:30.113606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47ad3b294cbb'
down_revision: Union[str, Sequence[str], None] = '51f33345d418'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metodos_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('propietario_tipo', sa.String(), nullable=False),
    sa.Column('propietario_id', sa.Integer(), nullable=False),
    sa.Column('tipo_pago', sa.String(), nullable=False),
    sa.Column('alias', sa.String(), nullable=True),
    sa.Column('referencia_token', sa.String(), nullable=True),
    sa.Column('qr_imagen_ruta', sa.String(), nullable=True),
    sa.Column('datos_adicionales', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metodos_pago_id'), 'metodos_pago', ['id'], unique=False)
    op.create_index(op.f('ix_metodos_pago_propietario_id'), 'metodos_pago', ['propietario_id'], unique=False)
    op.create_index(op.f('ix_metodos_pago_propietario_tipo'), 'metodos_pago', ['propietario_tipo'], unique=False)
    op.create_table('archivos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entidad_tipo', sa.String(), nullable=False),
    sa.Column('entidad_id', sa.Integer(), nullable=False),
    sa.Column('nombre_original', sa.String(), nullable=False),
    sa.Column('nombre_interno', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('tamano_bytes', sa.Integer(), nullable=True),
    sa.Column('ruta', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('subido_por_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['subido_por_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_interno')
    )
    op.create_index(op.f('ix_archivos_entidad_id'), 'archivos', ['entidad_id'], unique=False)
    op.create_index(op.f('ix_archivos_entidad_tipo'), 'archivos', ['entidad_tipo'], unique=False)
    op.create_index(op.f('ix_archivos_id'), 'archivos', ['id'], unique=False)
    op.create_table('clasificaciones_incidente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('categoria_incidente', sa.String(), nullable=False),
    sa.Column('subcategoria_incidente', sa.String(), nullable=True),
    sa.Column('nivel_prioridad', sa.String(), nullable=False),
    sa.Column('requiere_grua', sa.Boolean(), nullable=True),
    sa.Column('requiere_tecnico_especializado', sa.Boolean(), nullable=True),
    sa.Column('observaciones_modelo', sa.String(), nullable=True),
    sa.Column('confianza_modelo', sa.Float(), nullable=True),
    sa.Column('fuente_clasificacion', sa.String(), nullable=False),
    sa.Column('estado_revision', sa.String(), nullable=False),
    sa.Column('reportada_como_incorrecta', sa.Boolean(), nullable=True),
    sa.Column('motivo_reporte_cliente', sa.String(), nullable=True),
    sa.Column('revisada_por_usuario_id', sa.Integer(), nullable=True),
    sa.Column('observacion_revision', sa.String(), nullable=True),
    sa.Column('fecha_revision', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['revisada_por_usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitudes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clasificaciones_incidente_id'), 'clasificaciones_incidente', ['id'], unique=False)
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('metodo_pago_tipo', sa.String(), nullable=False),
    sa.Column('metodo_pago_referencia_id', sa.Integer(), nullable=True),
    sa.Column('proveedor_pasarela', sa.String(), nullable=True),
    sa.Column('referencia_externa', sa.String(), nullable=True),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('estado_pago', sa.String(), nullable=False),
    sa.Column('fecha_pago', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verificado_por_usuario_id', sa.Integer(), nullable=True),
    sa.Column('fecha_verificacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observacion', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['metodo_pago_referencia_id'], ['metodos_pago.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitudes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verificado_por_usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('solicitud_id')
    )
    op.create_index(op.f('ix_pagos_id'), 'pagos', ['id'], unique=False)
    op.create_table('recomendaciones_sucursal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('sucursal_recomendada_id', sa.Integer(), nullable=False),
    sa.Column('score_recomendacion', sa.Float(), nullable=False),
    sa.Column('criterios_evaluados', sa.String(), nullable=False),
    sa.Column('justificacion_recomendacion', sa.String(), nullable=False),
    sa.Column('precio_estimado', sa.Float(), nullable=True),
    sa.Column('distancia_estimada', sa.Float(), nullable=True),
    sa.Column('recomendacion_activa', sa.Boolean(), nullable=True),
    sa.Column('creada_por_ia', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitudes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sucursal_recomendada_id'], ['sucursales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recomendaciones_sucursal_id'), 'recomendaciones_sucursal', ['id'], unique=False)
    op.create_table('comisiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=False),
    sa.Column('pago_id', sa.Integer(), nullable=False),
    sa.Column('monto_base', sa.Float(), nullable=False),
    sa.Column('porcentaje_comision', sa.Float(), nullable=False),
    sa.Column('monto_comision', sa.Float(), nullable=False),
    sa.Column('pagado', sa.Boolean(), nullable=True),
    sa.Column('fecha_calculo', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_pago_comision', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registrado_por_usuario_id', sa.Integer(), nullable=True),
    sa.Column('observacion', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pago_id'], ['pagos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['registrado_por_usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitudes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnicos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('solicitud_id')
    )
    op.create_index(op.f('ix_comisiones_id'), 'comisiones', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comisiones_id'), table_name='comisiones')
    op.drop_table('comisiones')
    op.drop_index(op.f('ix_recomendaciones_sucursal_id'), table_name='recomendaciones_sucursal')
    op.drop_table('recomendaciones_sucursal')
    op.drop_index(op.f('ix_pagos_id'), table_name='pagos')
    op.drop_table('pagos')
    op.drop_index(op.f('ix_clasificaciones_incidente_id'), table_name='clasificaciones_incidente')
    op.drop_table('clasificaciones_incidente')
    op.drop_index(op.f('ix_archivos_id'), table_name='archivos')
    op.drop_index(op.f('ix_archivos_entidad_tipo'), table_name='archivos')
    op.drop_index(op.f('ix_archivos_entidad_id'), table_name='archivos')
    op.drop_table('archivos')
    op.drop_index(op.f('ix_metodos_pago_propietario_tipo'), table_name='metodos_pago')
    op.drop_index(op.f('ix_metodos_pago_propietario_id'), table_name='metodos_pago')
    op.drop_index(op.f('ix_metodos_pago_id'), table_name='metodos_pago')
    op.drop_table('metodos_pago')
    # ### end Alembic commands ###
