"""Add limits, sucursal_id and is_owner

Revision ID: 759e0c228111
Revises: 40b6c4cc9db4
Create Date: 2026-04-25 23:11:25.027390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '759e0c228111'
down_revision: Union[str, Sequence[str], None] = '40b6c4cc9db4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_rol_permiso', 'rol_permiso', ['rol_id', 'permiso_id'])
    op.add_column('suscripciones', sa.Column('max_sucursales', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('suscripciones', sa.Column('max_usuarios', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('usuarios', sa.Column('is_owner', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('usuarios', sa.Column('sucursal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'usuarios', 'sucursales', ['sucursal_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.drop_column('usuarios', 'sucursal_id')
    op.drop_column('usuarios', 'is_owner')
    op.drop_column('suscripciones', 'max_usuarios')
    op.drop_column('suscripciones', 'max_sucursales')
    op.drop_constraint('uq_rol_permiso', 'rol_permiso', type_='unique')
    # ### end Alembic commands ###
