"""fix: recomendacion criterios to json

Revision ID: f414c7277d1a
Revises: 47ad3b294cbb
Create Date: 2026-04-26 19:59:29.083747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f414c7277d1a'
down_revision: Union[str, Sequence[str], None] = '47ad3b294cbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recomendaciones_sucursal', 'criterios_evaluados',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=False,
               postgresql_using='criterios_evaluados::json')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recomendaciones_sucursal', 'criterios_evaluados',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
