"""Add partial unique index for owner

Revision ID: f50db8b6813d
Revises: 759e0c228111
Create Date: 2026-04-25 23:23:30.667364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f50db8b6813d'
down_revision: Union[str, Sequence[str], None] = '759e0c228111'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_unique_owner_per_empresa', 'usuarios', ['empresa_id'], unique=True, postgresql_where=sa.text('is_owner = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_unique_owner_per_empresa', table_name='usuarios', postgresql_where=sa.text('is_owner = true'))
    # ### end Alembic commands ###
